[package]
name = "branch-destroyer"
version = "1.0.0"
authors = ["Andrew Varnerin <andrew@varnerin.info>"]

[dependencies]
clap = "2.26.2"
hyper = "0.10.13"
hyper-native-tls = "0.2.4"
serde = "1.0"
serde_json = "1.0.3"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
